export const dataDummy = [
  {
    id: "123",
    title: "title 1 community",
    type: "BY_THE_COMMUNITY",
    platform: " platform 1",
    isFeatured: true,
    date: "12-12-2012",
    authorName: "Eko Sanjaya",
    authorImage: "https://via.placeholder.com/50",
    content: "blablabla",
    layout: "RED",
    isLike: false,
    totalLike: 10,
    isLove: true,
    totalLove: 10,
    isClap: false,
    totalClap: 10,
    postAssets: [
      {
        id: "1",
        url: "https://via.placeholder.com/250",
        type: "IMAGE",
      },
    ],
    postProducts: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
      },
    ],
  },
  {
    id: "124",
    type: "BY_NARS",
    title: "title 1 community",
    platform: " platform 1",
    isFeatured: true,
    date: "12-12-2012",
    authorName: "Eko Sanjaya",
    authorImage: "https://via.placeholder.com/50",
    content: "blablabla",
    layout: "weibo",
    isLike: false,
    totalLike: 10,
    isLove: true,
    totalLove: 10,
    isClap: false,
    totalClap: 10,
    postAssets: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
        type: "IMAGE",
      },
      {
        id: "2",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
        type: "IMAGE",
      },
      {
        id: "3",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
        type: "IMAGE",
      },
    ],
    postProducts: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
      },
    ],
  },
  {
    id: "125",
    title: "title 1 community",
    type: "BY_THE_COMMUNITY",
    platform: " platform 1",
    isFeatured: true,
    date: "12-12-2012",
    authorName: "Eko Sanjaya",
    authorImage: "https://via.placeholder.com/50",
    content: "blablabla",
    layout: "RED",
    isLike: false,
    totalLike: 10,
    isLove: true,
    totalLove: 10,
    isClap: false,
    totalClap: 10,
    postAssets: [
      {
        id: "1",
        url: "https://via.placeholder.com/250",
        type: "IMAGE",
      },
      {
        id: "2",
        url: "https://naver.github.io/egjs-infinitegrid/assets/image/2.jpg",
        type: "IMAGE",
      },
      {
        id: "3",
        url: "https://via.placeholder.com/250",
        type: "IMAGE",
      },
      {
        id: "4",
        url: "https://naver.github.io/egjs-infinitegrid/assets/image/2.jpg",
        type: "IMAGE",
      },
      {
        id: "5",
        url: "https://via.placeholder.com/250",
        type: "IMAGE",
      },
      {
        id: "6",
        url: "https://naver.github.io/egjs-infinitegrid/assets/image/2.jpg",
        type: "IMAGE",
      },
      {
        id: "7",
        url: "https://via.placeholder.com/250",
        type: "IMAGE",
      },
      {
        id: "8",
        url: "https://naver.github.io/egjs-infinitegrid/assets/image/2.jpg",
        type: "IMAGE",
      },
      {
        id: "9",
        url: "https://naver.github.io/egjs-infinitegrid/assets/image/2.jpg",
        type: "IMAGE",
      },
    ],
    postProducts: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
      },
    ],
  },
  {
    id: "126",
    type: "BY_NARS",
    title: "title 1 community",
    platform: " platform 1",
    isFeatured: true,
    date: "12-12-2012",
    authorName: "Eko Sanjaya",
    authorImage: "https://source.unsplash.com/kbPZmDxPK9M",
    content: "blablabla",
    layout: "VIDEO",
    isLike: false,
    totalLike: 10,
    isLove: true,
    totalLove: 10,
    isClap: false,
    totalClap: 10,
    postAssets: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
        type: "IMAGE",
      },
    ],
    postProducts: [
      {
        id: "1",
        url: "https://source.unsplash.com/kbPZmDxPK9M",
      },
    ],
  },
];
